import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/usr/local/bin/elvish"

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true

[font]
normal = { family = "Iosevka Term", style = "Regular" }
bold = { family = "Iosevka Term", style = "Bold" }
italic = { family = "Iosevka Term", style = "Italic" }
bold_italic = { family = "Iosevka Term", style = "BoldItalic" }

size = 12

[mouse]
hide_when_typing = true

